### ISSUE TITLE
Pydantic Validation Failed When Running examples/local/text-generation-bloom-example.py

### ISSUE THREAD

**Issue by knwng** [microsoft/DeepSpeed-MII#156] opened 2023-03-06 10:31 UTC
Hi, guys I'm new to this project and when I tried to run the example code `examples/local/text-generation-bloom-example.py`, I got a ValidationError and the subprocess failed to start, the traceback was like:
```
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
  File "/usr/local/lib/python3.8/dist-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mii/launch/multi_gpu_server.py", line 56, in main
    main()
    main()
  File "/usr/local/lib/python3.8/dist-packages/mii/launch/multi_gpu_server.py", line 56, in main
  File "/usr/local/lib/python3.8/dist-packages/mii/launch/multi_gpu_server.py", line 56, in main
    inference_pipeline = load_models(task_name=args.task_name,
  File "/usr/local/lib/python3.8/dist-packages/mii/models/load_models.py", line 84, in load_models
    inference_pipeline = load_models(task_name=args.task_name,
    inference_pipeline = load_models(task_name=args.task_name,
  File "/usr/local/lib/python3.8/dist-packages/mii/models/load_models.py", line 84, in load_models
  File "/usr/local/lib/python3.8/dist-packages/mii/models/load_models.py", line 84, in load_models
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 309, in init_inference
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 309, in init_inference
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 309, in init_inference
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/config_utils.py", line 61, in __init__
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/config_utils.py", line 61, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/config_utils.py", line 61, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mii/launch/multi_gpu_server.py", line 70, in <module>
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
    main()
  File "/usr/local/lib/python3.8/dist-packages/mii/launch/multi_gpu_server.py", line 56, in main
    inference_pipeline = load_models(task_name=args.task_name,
  File "/usr/local/lib/python3.8/dist-packages/mii/models/load_models.py", line 84, in load_models
    engine = deepspeed.init_inference(getattr(inference_pipeline,
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/__init__.py", line 309, in init_inference
    ds_inference_config = DeepSpeedInferenceConfig(**config_dict)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/config_utils.py", line 61, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DeepSpeedInferenceConfig
checkpoint
  str type expected (type=type_error.str)
[2023-03-06 10:06:06,902] [INFO] [server_client.py:117:_wait_until_server_is_live] waiting for server to start...
[2023-03-06 10:06:08,013] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 32490
[2023-03-06 10:06:08,014] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 32491
[2023-03-06 10:06:08,014] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 32492
[2023-03-06 10:06:08,015] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 32493
```

Then I printed the configuration who failed the validation, it's like:
```
inf_config: {'tensor_parallel': {'tp_size': 4, 'mpu': None}, 'dtype': torch.float16, 'replace_method': 'auto', 'enable_cuda_graph': False, 'checkpoint': {'type': 'BLOOM', 'checkpoints': {'non_tp': ['non-tp.pt'], 'tp': ['tp_00_
00.pt', 'tp_01_00.pt', 'tp_02_00.pt', 'tp_03_00.pt', 'tp_04_00.pt', 'tp_05_00.pt', 'tp_06_00.pt', 'tp_07_00.pt', 'tp_00_01.pt', 'tp_01_01.pt', 'tp_02_01.pt', 'tp_03_01.pt', 'tp_04_01.pt', 'tp_05_01.pt', 'tp_06_01.pt', 'tp_07_0
1.pt', 'tp_00_02.pt', 'tp_01_02.pt', 'tp_02_02.pt', 'tp_03_02.pt', 'tp_04_02.pt', 'tp_05_02.pt', 'tp_06_02.pt', 'tp_07_02.pt', 'tp_00_03.pt', 'tp_01_03.pt', 'tp_02_03.pt', 'tp_03_03.pt', 'tp_04_03.pt', 'tp_05_03.pt', 'tp_06_03
.pt', 'tp_07_03.pt', 'tp_00_04.pt', 'tp_01_04.pt', 'tp_02_04.pt', 'tp_03_04.pt', 'tp_04_04.pt', 'tp_05_04.pt', 'tp_06_04.pt', 'tp_07_04.pt', 'tp_00_05.pt', 'tp_01_05.pt', 'tp_02_05.pt', 'tp_03_05.pt', 'tp_04_05.pt', 'tp_05_05.
pt', 'tp_06_05.pt', 'tp_07_05.pt', 'tp_00_06.pt', 'tp_01_06.pt', 'tp_02_06.pt', 'tp_03_06.pt', 'tp_04_06.pt', 'tp_05_06.pt', 'tp_06_06.pt', 'tp_07_06.pt', 'tp_00_07.pt', 'tp_01_07.pt', 'tp_02_07.pt', 'tp_03_07.pt', 'tp_04_07.p
t', 'tp_05_07.pt', 'tp_06_07.pt', 'tp_07_07.pt']}, 'version': 1, 'parallelization': 'tp', 'tp_size': 8, 'dtype': 'float16', 'base_dir': '/data/bloom-mp/models--microsoft--bloom-deepspeed-inference-fp16/snapshots/648a475e3cfb59
dbe44f69a82725a772c9bd7f01'}, 'config': None, 'training_mp_size': 1, 'replace_with_kernel_inject': True}
```

After reading the source code, I think the problem may be related to this line: https://github.com/microsoft/DeepSpeed-MII/blob/main/mii/models/load_models.py#L64, where a dict is assigned to 'checkpoint' who only accepts str.

But since it's my day one to use this project, I'm not sure it's a bug or intended. I'm willing to help with some instructions. Thanks!

**Comment by knwng** [comment] 2023-03-06 10:39
FYI, I changed the 'tensor_parallel' item in `mii_configs` from 8 to 4 since there's only 4 GPUs available. I'm not sure if that's related.

**Comment by mrwyattii** [comment] 2023-03-06 19:28
@knwng thanks for reporting this. This error is due to a recent refactor we did with DeepSpeed-inference. Could you please try this branch and let me know if that fixes the error?
`pip install git+https://github.com/microsoft/DeepSpeed-MII@mrwyattii/fix-checkpoint-config`

**Comment by knwng** [comment] 2023-03-08 03:08
Hi @mrwyattii, I've just tried this version but got more ValidationErrors😂
![Screenshot 2023-03-08 at 11 07 19](https://user-images.githubusercontent.com/26247277/223609676-95b4e03d-fba8-403e-b0e9-37caea25fd7d.png)

**Comment by mrwyattii** [comment] 2023-03-10 19:23
Hi @knwng sorry that didn't fix the problem. I see that the problem is with the DeepSpeed inference config class. I just tested this and it's working for me. Could you please try this DeepSpeed branch (don't use the DeepSpeed-MII branch I create prior, just use DeepSpeed-MII@main):
`pip install git+https://github.com/mrwyattii/DeepSpeed@inf-checkpoint-config git+https://github.com/microsoft/DeepSpeed-MII`

Please let me know if this fixes the validation errors!

**Comment by knwng** [comment] 2023-03-13 07:56
Hi @mrwyattii, I encountered an OOM since I only have 4 T4 GPUs available when it requires 8, but I think this fixed the validation errors.

**Comment by mrwyattii** [comment] 2023-03-14 18:02
> Hi @mrwyattii, I encountered an OOM since I only have 4 T4 GPUs available when it requires 8, but I think this fixed the validation errors.

Great, I'll get this fixed merged on the DeepSpeed side and close the issue. Please open another issue if you are unable to get the Bloom model up and running. Just FYI: with FP16, I believe the Bloom-176 model requires 8x80GB A100 GPUs to load. You may want to try running one of the smaller variants (e.g., `bigscience/bloom-7b1`)

**Closed by mrwyattii** 2023-03-14 18:02 UTC
